apiVersion: v1
kind: Pod
metadata:
  name: docker-build-push
spec:
  containers:
  - name: docker
    image: docker:1.9.1
    command: ["docker", "build", "-t", "ndslabs/jenkins", "/home/demo/jenkins-experiment"]
    resources:
      limits:
        cpu: "500m"
        memory: 100M
      requests:
        cpu: "100m"
        memory: 100M
    securityContext: 
      privileged: true
    volumeMounts: 
    - name: dockersock 
      mountPath: /var/run/docker.sock
    - name: home 
      mountPath: /home/demo
  restartPolicy: Never
  volumes:
  - name: dockersock
    hostPath:
      path: /var/run/docker.sock
  - name: home
    hostPath:
      path: /home/core
