apiVersion: v1
kind: ReplicationController
metadata:
  name: jenkins
spec:
  replicas: 1
  selector:
    component: jenkins
  template:
    metadata:
      labels:
        component: jenkins
    spec:
      containers:
      - name: jenkins
        image: ndslabs/jenkins:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 50000
          protocol: TCP
        volumeMounts:
        - mountPath: /var/jenkins-home
          name: jenkins
        - mountPath: /var/run/docker.sock
          name: dockersock
      volumes:
      - hostPath:
          path: /var/run/docker.sock
        name: dockersock
      - hostPath:
          path: /var/jenkins-home
        name: jenkins
