apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    component: jenkins
spec:
  selector:
    component: jenkins
  ports:
    - port: 8080
      protocol: TCP
      nodePort: 30009
      name: http
    - port: 50000
      protocol: TCP
      nodePort: 30010
      name: cli
  type: NodePort
